### ISSUE TITLE
你的language.php貌似有bug

### ISSUE THREAD

**Issue by mountainguan** [Neroxiezi/PHP-ML-study#1]
1.官方的例子能跑，你的例子不能跑
2.但是官方的例子没有直接进行预测句子的操作，你这里有

所以能不能把你的language.php代码梳理一下，我也不知道是不是我的php-ml是0.4.1的问题

**Comment by pfinal-nc** [comment]
@mountainguan  嘿 兄弟 谢谢你提出bug, language.php 这个是有bug的  因为地下 用了 StratifiedRandomSplit 样本分组 所以下面预测的数据 应该是  predict($randomSplit->getTestSamples()) 而非我自定义的数组。

**Comment by mountainguan** [comment]
@Neroxiezi 那你有自定义数组的例子吗？我到现在都没搞懂自定义数组怎么在这个例子中实现

**Comment by pfinal-nc** [comment]
@mountainguan 这个例子包含的算法比较的多  如果是单独的 学 svc 支持向量,这里有一个 svc.php的单独的svc例子, 在language这个例子中 用到了  分词器,向量器,特征提取,数据处理,这个例子是用来给数据分类用

**Comment by pfinal-nc** [comment]
@mountainguan  我做了一个简单的language-simple.php  你看看

**Comment by mountainguan** [comment]
@Neroxiezi 你的是php7.1吗，我这边是7.0跑不动这段代码，在分词那里有报错

**Comment by mountainguan** [comment]
@Neroxiezi 解决了，对了你这里是没有中分分词器的，如果有需要我可以提供一个中文分词的思路给你。

**Comment by pfinal-nc** [comment]
@mountainguan 好的, 有需要的，谢谢了

**Comment by mountainguan** [comment]
@Neroxiezi https://packagist.org/packages/scws/pscws4 这个库而已实现基础的分词功能，这个叫scws的项目可以引入到php-ml里的分词器里专门为中文进行分词

**Comment by pfinal-nc** [comment]
@mountainguan  谢谢, scws 单独用过,配合这个还真的没有用过,我先学习学习
